version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: securevision
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgresql://admin:admin123@postgres:5432/securevision
      REDIS_URL: redis://redis:6379
  detector:
    build: ./ml
    depends_on:
      - backend
    environment:
      VIDEO_PATH: /app/video/13384448_1920_1080_30fps.mp4
      API_URL: http://backend:8000
    volumes:
      - ./ml:/app 

volumes:
  postgres_data: